### ISSUE TITLE
No Files Saved Following FileDialog

### ISSUE THREAD

**Issue by tomcolley1962** [bollandj/msasciitab#2]
I've recently installed the ASCII Tab Export plugin. It won't save tab files.

### What Happens
- I click on Plugins > ASCII Tab Exporter > Export ASCII Tab
- The File Save dialog appears. 
- I enter a filename and folder and click save
- I check the folder contents
- I find there is no file with that filename

### What I Expect to Happen
- As above but when I check folder contents, I find the exported tab file.

I've run the plugin with two musescore tabs containing tablature. It failed with both scores. One was downloaded from here: https://musescore.com/user/28842914/scores/5154865

I ran the plugin from Plugin Creator and got the following Debug output:
```
Running…
Plugin Details:
  Menu Path: Plugins.ASCII Tab Exporter.Export ASCII tab
  Version: 0.2
  Description: Generates an ASCII tab
  Requires Score
Debug: Start
Debug: Path: /home/tom/Documents/MuseScore3/Plugins/msasciitab-master
Debug: Filename: PachabelCanonInD_Yonah_Tab.mscz
Warning: Model size of -92 is less than 0
Warning: Model size of -4 is less than 0
Debug: New bar! (#1)
Debug: ________________________________________
Debug: Bar 1
Debug: Current time signature: 4/4
Debug: Indices 0 - 6
Debug: barIdxTotal: 48, lineLengthLimit: 112
Debug: ________________________________________
Debug: Bar 1
Debug: Current time signature: 4/4
Debug: Indices 6 - 12
Debug: barIdxTotal: 48, lineLengthLimit: 112
171:-1: TypeError: Cannot read property 'position' of undefined
171:-1: TypeError: Cannot read property 'position' of undefined
171:-1: TypeError: Cannot read property 'position' of undefined
Warning: <Unknown File>:171: TypeError: Cannot read property 'position' of undefined
```
### My System
OS: Ubuntu 20.04
Musescore Version: 3.2.3
ASCII Tab Exporter Version: 0.2

**Comment by Jojo-Schmitz** [comment]
`firstTiedNote` needs MuseScore 3.3 or later

**Comment by bollandj** [comment]
Thanks @Jojo-Schmitz, have updated the README with a note about version requirement.
